### PR TITLE
Allow symfony 7

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by mishac** [comment]
Any idea when this will be able to be merged?  It's our last dependency we need before moving to symfony 7.  Happy to help in any way if I can.

**Comment by VincentLanglet** [comment]
One day or two. I wait for a release of https://github.com/composer-unused/composer-unused/pull/590#issuecomment-1831804438

**Comment by mishac** [comment]
great thanks!

**Comment by VincentLanglet** [comment]
I also need https://github.com/composer-unused/symbol-parser/pull/121

**Comment by VincentLanglet** [comment]
> Would love to see a release 😃

I made a lot of refacto on this lib, with some BC break, so it's required to be a 2.0.0 
Would you be ok to test the main branch on your side @OskarStark  (I can make a RC release if needed).

**Comment by VincentLanglet** [comment]
@mishac @OskarStark I released 2.0.0-rc-1, please tell me if everything is fine on your side :)

**Pull request merged**
