### PR TITLE
Fix windows support

### LINKED ISSUE #193: FileNameRule not works
### Rule(s) related to or rule(s) missing

`FileNameRule`

### Expected behavior

`FileNameRule` should report errors to me.

### Actual behavior

I download Symfony with `symfony new myproject --php=8.2 --webapp --docker --cloud`

Then I download this bundle with `symfony composer require --dev vincentlanglet/twig-cs-fixer`

I put this config 

```php
// .twig-cs-fixer.php

<?php

use TwigCsFixer\Rules\File\FileNameRule;

$ruleset = new TwigCsFixer\Ruleset\Ruleset();
$ruleset->addRule(new FileNameRule(baseDirectory: 'templates', ignoredSubDirectories: ['bundles']));

$config = new TwigCsFixer\Config\Config();
$config->setRuleset($ruleset);
$config->setCacheFile(null);

return $config;
```

I rename `templates/base.twig.html` by `templates/Xbase.twig.html` for test this rule.

I execute `vendor\bin\twig-cs-fixer lint` but I have no errors.

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes #193

### CODE REVIEW

**Comment by seb-jean** [comment]
It works.

**Comment by VincentLanglet** [comment]
> It works.

Ok, I'll try to add a CI for windows then I'll merge this and release it.

**Comment by VincentLanglet** [comment]
Can you confirm this still works fine for you @seb-jean ?

Do you get a nice render of the errors in your console ?

**Comment by seb-jean** [comment]
I have an error :
`Warning: Undefined array key 15 in {...}\vendor\vincentlanglet\twig-cs-fixer\src\Report\Reporter\TextReporter.php on line 117`

**Comment by VincentLanglet** [comment]
> I have an error : `Warning: Undefined array key 15 in {...}\vendor\vincentlanglet\twig-cs-fixer\src\Report\Reporter\TextReporter.php on line 117`

Here https://github.com/VincentLanglet/Twig-CS-Fixer/pull/196/files#diff-f9506c2d1272ccbfc89aaf636c36724ec6c6118c134f6e9c96c6dc672ee2fcb6R109

Can you dump `$templates`, `$lines` and `$line` ?

**Comment by seb-jean** [comment]
$template 

```
^ """
<!DOCTYPE html>\n
<html>\n
    <head>\n
        <meta charset="UTF-8">\n
        <title>{% block title %}Welcome!{% endblock %}</title>\n
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">\n
        {% block stylesheets %}\n
        {% endblock %}\n
\n
        {% block javascripts %}\n
{% block importmap %}{{ importmap('app') }}{% endblock %}\n
        {% endblock %}\n
    </head>\n
    <body>\n
        {% block body %}{% endblock %}\n
        {% set Test = 'a' %}\n
{#  </body> #}\n
</html>\n
\n
\n
"""
```

$lines

```
^ array:1 [
  0 => """
    <!DOCTYPE html>\n
    <html>\n
        <head>\n
            <meta charset="UTF-8">\n
            <title>{% block title %}Welcome!{% endblock %}</title>\n
            <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text><text y=%221.3em%22 x=%220.2em%22 font-size=%2276%22 fill=%22%23fff%22>sf</text></svg>">\n
            {% block stylesheets %}\n
            {% endblock %}\n
    \n
            {% block javascripts %}\n
    {% block importmap %}{{ importmap('app') }}{% endblock %}\n
            {% endblock %}\n
        </head>\n
        <body>\n
            {% block body %}{% endblock %}\n
            {% set Test = 'a' %}\n
    {#  </body> #}\n
    </html>\n
    \n
    \n
    """
]
```

$line 
17

**Comment by VincentLanglet** [comment]
> I feel like you're on Windows but your template is using \n for EOL.

Ok so it's indeed the fact that:
- You running the tool on windows
- the file use `\n` as EOL.

Can you try the latest commit ?

**Pull request merged**
