### PR TITLE
Improve include rule

### PR DESCRIPTION
**Pull request by VincentLanglet**
I was curious about how hard it would be to handle whitespace in the include rules, and that doesn't seems that hard

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@smnandre I tried to play with the rule to see if it was easy to handle whitespace. Do you think it's worth it to add this ?

**Comment by smnandre** [comment]
To be honest... i don't know (not a false-way of saying i don't like... i really don"t know)

Option A: a fixer does only one thing
- pros: when "atomic", it's easier to test, maintain, update, etc... 
- cons: code will really soon become duplicated in a lot of places, and become less readable

Option B: a fixer has to produce correct code
- pros: easier to test, no nested calls, etc. 
- cons: tests are ugly and force us to expect weird things like multiple spaces

Maybe there is a "C" option which would be a mix of A and having test helpers that do call others fixers before comparing expected / produced ?

**Comment by VincentLanglet** [comment]
> To be honest... i don't know (not a false-way of saying i don't like... i really don"t know)
> 
> Option A: a fixer does only one thing
> 
> * pros: when "atomic", it's easier to test, maintain, update, etc...
> * cons: code will really soon become duplicated in a lot of places, and become less readable
> 
> Option B: a fixer has to produce correct code
> 
> * pros: easier to test, no nested calls, etc.
> * cons: tests are ugly and force us to expect weird things like multiple spaces
> 
> Maybe there is a "C" option which would be a mix of A and having test helpers that do call others fixers before comparing expected / produced ?

The C option is not a bad idea: this would be 
https://github.com/VincentLanglet/Twig-CS-Fixer/pull/179/files if I understand correctly the suggestion

**Comment by smnandre** [comment]
Oh this is cleaner and simpler than what i had in mind 👏

**Pull request closed without merging**
