### PR TITLE
Add indent sniff

### PR DESCRIPTION
**Pull request by VincentLanglet**

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@alexander-schranz Can you confirm it works for you and does what you were looking for ?

**Comment by alexander-schranz** [comment]
@VincentLanglet First thank you for working on this 🙏 .

It seems correctly detect `tabs` but example false indention of spaces is not detected e.g.:

```twig
{% extends '@AvodiExtranet/base.html.twig' %}

{% block menu %}
   {% endblock %} {# 3 spaces #}

{% block main %}
  {% endblock %} {# 2 spaces #}

{% block footer %}
 {% endblock %} {# 1 spaces #}
```

Not sure if that would also be easy possible 🤔

**Comment by VincentLanglet** [comment]
> It seems correctly detect `tabs` but example false indention of spaces is not detected e.g.:
> 
> ```
> {% extends 'base.html.twig' %}
> 
> {% block menu %}
>    {% endblock %} {# 3 spaces #}
> 
> {% block main %}
>   {% endblock %} {# 2 spaces #}
> 
> {% block footer %}
>  {% endblock %} {# 1 spaces #}
> ```
> 
> Not sure if that would also be easy possible 🤔

To me that's a totally different rule:
- This one is converting tab to space
- You're looking for a rule which fix space indent

Also, in the example
```
{% set foo = bar %} {# 1 spaces #}
 {% block footer %}
```
I cannot say if we want to fix this to 0 or 4 spaces.
And we'll soon end up with non-solvable issue like https://github.com/VincentLanglet/Twig-CS-Fixer/issues/47 ^^'

**Comment by alexander-schranz** [comment]
Then looks fine for me :)

Understand a whole indention fix is really hard, what maybe could be possible check if a `{% end.. %}` tag is on the same indention level or same line. But as you said that would be a different rule 👍

**Comment by alexander-schranz** [comment]
@VincentLanglet Thank you and congratulation for 1.0.0 🎉

**Comment by VincentLanglet** [comment]
> @VincentLanglet Thank you and congratulation for 1.0.0 🎉

Thanks.
It's been years I use this without issues, so it was time for a stable version ^^

**Pull request merged**
